services:

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: CurrencyConverter/Dockerfile
    container_name: api
    ports:
      - "5000:8080"
    depends_on:
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Redis=redis